repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff Linter
        entry: uv run ruff check
        language: system
        types: [python]
        require_serial: true
      - id: mypy
        name: Mypy Type Checker
        entry: uv run mypy .
        language: system
        types: [python]
        require_serial: true
